# Generated by Django 4.0.5 on 2022-12-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/plants/')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/plants/type/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(blank=True, max_length=200, null=True)),
                ('tozlayici', models.CharField(blank=True, max_length=200, null=True)),
                ('mehsul_zamani', models.CharField(max_length=200)),
                ('meyve_agirligi', models.CharField(blank=True, max_length=200, null=True)),
                ('qabigli_meyve_boyu', models.FloatField(blank=True, null=True)),
                ('rengi', models.CharField(blank=True, max_length=200, null=True)),
                ('meyve_ic_rengi', models.CharField(blank=True, max_length=200, null=True)),
                ('formasi', models.CharField(blank=True, max_length=200, null=True)),
                ('kalibr', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plants')),
            ],
        ),
    ]
