# Generated by Django 4.0.5 on 2023-01-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_plant_mehsul_zamani'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='ic_meyve_boyu',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
