# Generated by Django 4.0.5 on 2023-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_plant_ic_meyve_boyu'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='qabigli_meyve_agirligi',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
