# Generated by Django 4.0.5 on 2023-01-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plant_qabigli_meyve_agirligi'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='lepe_agirligi',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
