# Generated by Django 4.0.5 on 2023-02-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_plant_lepe_agirligi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/techniques/')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('marka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('urun_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ürün kodu')),
                ('tank', models.IntegerField(blank=True, null=True, verbose_name='Tank')),
                ('pompa', models.IntegerField(blank=True, null=True, verbose_name='Pompa')),
                ('traktor_gucu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Traktor Gücü')),
                ('tezyiq', models.IntegerField(blank=True, null=True, verbose_name='Təzyiq')),
                ('hava', models.IntegerField(blank=True, null=True, verbose_name='Hava')),
                ('agirliq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ağırlıq')),
                ('is_hecmi', models.IntegerField(blank=True, null=True, verbose_name='İş həcmi')),
                ('enerji_menbeyi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enerji mənbəyi')),
                ('qaranti', models.IntegerField(blank=True, null=True, verbose_name='Qarantiya')),
                ('saatliq_mehsul', models.CharField(blank=True, max_length=100, null=True, verbose_name='Saatlıq məhsul')),
                ('ayirma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ayırma')),
                ('enerji_ehtiyaci', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enerji ehtiyacı')),
                ('guc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Güc')),
                ('hecm', models.CharField(blank=True, max_length=100, null=True, verbose_name='Həcm')),
                ('motor_gucu', models.IntegerField(blank=True, null=True, verbose_name='Motor gücü')),
                ('guc_telebati', models.IntegerField(blank=True, null=True, verbose_name='Güc tələbatı')),
                ('bicaq_sayi', models.IntegerField(blank=True, null=True, verbose_name='Bıçaq sayı')),
                ('kazan_hacmi', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('calisma_yuksekligi', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('calisma_uzunlugu', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('calisma_yonu', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('ceviz_qurutma_qabilliyyeti', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('guc_gereksinimi', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('hidrolik_gereksinimi', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('traktor_orta_noktasindan_max_kol_uzunlugu', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('calisma_derinligi', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('capalama_genisligi', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('agac_sira_arasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='')),
                ('umumi_genislik', models.IntegerField(blank=True, null=True, verbose_name='Ümumi genişlik')),
                ('isleme_genisliyi', models.IntegerField(blank=True, null=True, verbose_name='İşləmə genişliyi')),
                ('ilerleme_sureti', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlərləmə sürəti')),
                ('texnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.texnika', verbose_name='Texnika')),
            ],
        ),
    ]
