# Generated by Django 4.0.5 on 2023-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_texnika_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='ozellik_1',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Özəllik 1'),
        ),
        migrations.AddField(
            model_name='model',
            name='ozellik_2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Özəllik 2'),
        ),
        migrations.AddField(
            model_name='model',
            name='ozellik_3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Özəllik 3'),
        ),
        migrations.AddField(
            model_name='model',
            name='ozellik_4',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Özəllik 4'),
        ),
        migrations.AlterField(
            model_name='model',
            name='agac_sira_arasi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ağac sıra arası'),
        ),
        migrations.AlterField(
            model_name='model',
            name='calisma_derinligi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Çalışma dərinliyi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='calisma_uzunlugu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma uzunluğu'),
        ),
        migrations.AlterField(
            model_name='model',
            name='calisma_yonu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma yönü'),
        ),
        migrations.AlterField(
            model_name='model',
            name='calisma_yuksekligi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma yüksəkliyi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='capalama_genisligi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Çapalama genişliyi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='ceviz_qurutma_qabilliyyeti',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ceviz qurutma qabiliyyəti'),
        ),
        migrations.AlterField(
            model_name='model',
            name='guc_gereksinimi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Güc gereksinimi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='hidrolik_gereksinimi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hidrolik gereksinimi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='kazan_hacmi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kazan həcmi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='traktor_orta_noktasindan_max_kol_uzunlugu',
            field=models.IntegerField(blank=True, null=True, verbose_name='Traktor orta nöqtəsindən max qol uzunluğu'),
        ),
    ]
