# Generated by Django 4.0.5 on 2023-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_model_ozellik_1_model_ozellik_2_model_ozellik_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='motor_gucu',
            field=models.FloatField(blank=True, null=True, verbose_name='Motor gücü'),
        ),
    ]
