# Generated by Django 4.0.5 on 2023-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_model_motor_gucu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('image', models.ImageField(upload_to='images/tools/')),
            ],
        ),
        migrations.AlterField(
            model_name='model',
            name='isleme_genisliyi',
            field=models.FloatField(blank=True, null=True, verbose_name='İşləmə genişliyi'),
        ),
        migrations.AlterField(
            model_name='model',
            name='umumi_genislik',
            field=models.FloatField(blank=True, null=True, verbose_name='Ümumi genişlik'),
        ),
    ]
