# Generated by Django 4.0.5 on 2023-02-05 12:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tool_alter_model_isleme_genisliyi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[252.13, 252.13], upload_to='images/tools/'),
        ),
    ]
