# Generated by Django 4.0.5 on 2023-02-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tool_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gübre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('element_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 1')),
                ('faiz_1', models.FloatField(blank=True, null=True, verbose_name='Faiz 1')),
                ('element_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 2')),
                ('faiz_2', models.FloatField(blank=True, null=True, verbose_name='Faiz 2')),
                ('element_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 3')),
                ('faiz_3', models.FloatField(blank=True, null=True, verbose_name='Faiz 3')),
                ('element_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 4')),
                ('faiz_4', models.FloatField(blank=True, null=True, verbose_name='Faiz 4')),
                ('element_5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 5')),
                ('faiz_5', models.FloatField(blank=True, null=True, verbose_name='Faiz 5')),
                ('element_6', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 6')),
                ('faiz_6', models.FloatField(blank=True, null=True, verbose_name='Faiz 6')),
                ('element_7', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 7')),
                ('faiz_7', models.FloatField(blank=True, null=True, verbose_name='Faiz 7')),
                ('element_8', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 8')),
                ('faiz_8', models.FloatField(blank=True, null=True, verbose_name='Faiz 8')),
                ('element_9', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 9')),
                ('faiz_9', models.FloatField(blank=True, null=True, verbose_name='Faiz 9')),
                ('element_10', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 10')),
                ('faiz_10', models.FloatField(blank=True, null=True, verbose_name='Faiz 10')),
                ('element_11', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 11')),
                ('faiz_11', models.FloatField(blank=True, null=True, verbose_name='Faiz 11')),
                ('element_12', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 12')),
                ('faiz_12', models.FloatField(blank=True, null=True, verbose_name='Faiz 12')),
                ('element_13', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 13')),
                ('faiz_13', models.FloatField(blank=True, null=True, verbose_name='Faiz 13')),
                ('element_14', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 14')),
                ('faiz_14', models.FloatField(blank=True, null=True, verbose_name='Faiz 14')),
                ('element_15', models.CharField(blank=True, max_length=200, null=True, verbose_name='Element 15')),
                ('faiz_15', models.FloatField(blank=True, null=True, verbose_name='Faiz 15')),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.ImageField(upload_to='images/tools/'),
        ),
    ]
