# Generated by Django 4.0.5 on 2023-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_gübre_image_alter_texnika_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gübre',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Məlumat'),
        ),
    ]
