# Generated by Django 4.0.5 on 2023-02-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gübre_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/watering')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad')),
                ('mehsul_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Məhsul kodu')),
                ('giris_cixis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giriş-çıxış')),
                ('hecm', models.CharField(blank=True, max_length=200, null=True, verbose_name='Həcm')),
                ('yosun_filteri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yosun Filteri')),
                ('plastik_filter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Plastik Filter')),
                ('avtomatik_filter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Avtomatik Filter')),
                ('qum_tanki', models.IntegerField(blank=True, null=True)),
                ('suzme_sethi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
