# Generated by Django 4.0.5 on 2023-02-23 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_watering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watering',
            name='avtomatik_filter',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='giris_cixis',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='hecm',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='mehsul_kodu',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='plastik_filter',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='qum_tanki',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='suzme_sethi',
        ),
        migrations.RemoveField(
            model_name='watering',
            name='yosun_filteri',
        ),
        migrations.CreateModel(
            name='Watering_tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mehsul_kodu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Məhsul kodu')),
                ('giris_cixis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Giriş-çıxış')),
                ('hecm', models.CharField(blank=True, max_length=200, null=True, verbose_name='Həcm')),
                ('yosun_filteri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Yosun Filteri')),
                ('plastik_filter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Plastik Filter')),
                ('avtomatik_filter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Avtomatik Filter')),
                ('qum_tanki', models.IntegerField(blank=True, null=True)),
                ('suzme_sethi', models.IntegerField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.watering')),
            ],
        ),
    ]
