# Generated by Django 4.0.5 on 2023-02-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_watering_avtomatik_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering_tool',
            name='content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Məlumat'),
        ),
    ]
